---
schema_class: MusicDB
resultsets:
    - Release
    - Track
fixture_sets:
    basic:
        Release:
            -
                - upc
                - title
            -
                - 666
                - Foo
            -
                - 777
                - Bar
        Track:
            -
                - release_id
                - title
                - sequence
                - volume_no
            -
                - 1
                - Track 1
                - 1
                - 1
            -
                - 1
                - Track 2
                - 2
                - 1
            -
                - 2
                - Bart1
                - 1
                - 1
            -
                - 2
                - Bart2
                - 2
                - 1
